<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <Description>Now we're talking. Send emails via SMTP.</Description>
    <AssemblyTitle>Fluent Email - SMTP</AssemblyTitle>
    <Authors>Luke Lowrey;Ben Cull;Github Contributors</Authors>
    <PackageTags>$(PackageTags);smtp</PackageTags>
    <TargetFrameworks>netstandard2.0;net8.0</TargetFrameworks>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\FluentEmail.Core\FluentEmail.Core.csproj" />
  </ItemGroup>

</Project>
