<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <Description>Send emails via Microsoft Graph API</Description>
    <AssemblyTitle>Fluent Email - Graph</AssemblyTitle>
    <PackageTags>$(PackageTags);graph</PackageTags>
    <TargetFramework>netstandard2.0</TargetFramework>
    <NoWarn>NU5104</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Graph" Version="5.105.0" />
    <PackageReference Include="Azure.Identity" Version="1.21.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\FluentEmail.Core\FluentEmail.Core.csproj" />
  </ItemGroup>

</Project>
